stock-alert:
  fcs-api-key: ${FCS-API-KEY}
  base-url: https://fcsapi.com/api-v3/stock
  update-cron: ${UPDATE-CRON:0 16 9-21 * * MON-FRI}
  config-url: ${CONFIG-URL:src/main/resources/config-example.json}
  run-on-startup:  ${UPDATE-ON-STARTUP:false}
  storage-provider: ${STORAGE:default}

spring:
  application:
    name: stock-alert

  mail:
    host:  ${GATEWAY-EMAIL-HOST:localhost}
    port: ${GATEWAY-EMAIL-PORT:587}
    username: ${GATEWAY-EMAIL-USER:}
    password: ${GATEWAY-EMAIL-PWD:}
    properties:
      mail:
        debug: ${GATEWAY-EMAIL-DEBUG:false}
        smtp:
          sender-address: ${GATEWAY-EMAIL-SENDER-ADDRESS:stock-alert@arburk.github.com}
          auth: ${GATEWAY-EMAIL-AUTH:true}
          starttls:
            enable: ${GATEWAY-EMAIL-TLS:true}
          ssl:
            enable: ${GATEWAY-EMAIL-SSL:true}

  cloud:
    s3:
      bucket: ${S3-BUCKET:stock-alert}
      credentials:
        access-key: ${S3-ACCESS-KEY:}
        secret-key: ${S3-SECRET-KEY:}
      region: ${S3-REGION:}
      endpoint:
        url: ${S3-ENDPOINT:}
        force-path-style: ${S3-ENDPOINT-FORCE-PATH-STYLE:true}

logging:
  level:
    com.github.arburk.stockalert: INFO
