name: CI

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'feat/**'
      - 'fix/**'
    paths:
      - src/**
      - pom.xml
  pull_request_target:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Maven build and sonar analysis
        id: maven
        run: |
          mvn -B package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=arburk_stock-alert --file pom.xml
          echo "version=$(mvn help:evaluate -Dexpression='project.version' -q -DforceStdout)" >> $GITHUB_OUTPUT
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: stock-alert.jar
          path: target/*.jar
          retention-days: 7

    outputs:
      artifact_version: ${{ steps.maven.outputs.version }}

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: stock-alert.jar
          path: target
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push stock-alert:${{ needs.build.outputs.artifact_version }}
        id: docker_build
        uses: docker/build-push-action@master
        with:
          context: .
          push: true
          tags: arburk/stock-alert:${{ needs.build.outputs.artifact_version }}